<a href="https://colab.research.google.com/github/govardhan-06/practice-Notebooks/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

###Scalars, Vectors, Tensors and Matrix

In [2]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.shape

torch.Size([])

In [5]:
 #vector
 vector=torch.tensor([7,8])
 vector

tensor([7, 8])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
vector[1]

tensor(8)

In [9]:
#matrix
matrix=torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
matrix[1]

tensor([ 9, 10])

In [13]:
#tensor
tensor=torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
tensor.ndim

3

In [15]:
tensor.shape

torch.Size([1, 3, 3])

In [16]:
tensor[0][1][1]

tensor(6)

###Random Tensors and Random image tensor


In [17]:
#Random Tensors
torch.rand(2,2,4)

tensor([[[0.7123, 0.9431, 0.3014, 0.3239],
         [0.5655, 0.0948, 0.0611, 0.0161]],

        [[0.8596, 0.6159, 0.0597, 0.2089],
         [0.0056, 0.8253, 0.6208, 0.9011]]])

In [18]:
#Random image tensors
randm_image_size_tensor=torch.rand(size=(224,224,3))
randm_image_size_tensor.shape,randm_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###Zeros and Ones

In [19]:
zeros=torch.zeros(size=(3,5))
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [20]:
ones=torch.ones(size=(1,4))
ones

tensor([[1., 1., 1., 1.]])

###Range of tensors and tensors like

In [21]:
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor Datatypes

In [23]:
float_32_tensor=torch.tensor(data=[3.0,6.0,9.0],
                             dtype=None,
                             device=None,
                             requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [24]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float_32_tensor*float_16_tensor

tensor([ 9., 36., 81.])

###Basic tensor related functions

In [26]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.8670, 0.2691, 0.6945, 0.7819],
        [0.1205, 0.0071, 0.7475, 0.8423],
        [0.9465, 0.9340, 0.0052, 0.6878]])

In [27]:
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Device tensor is stored on : {some_tensor.device}")

Shape of tensor : torch.Size([3, 4])
Datatype of tensor : torch.float32
Device tensor is stored on : cpu


###Tensor operations
* Addition
* Subtract
* Multiply
* Divide
* Matrix Multiplication


In [28]:
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [29]:
tensor-10

tensor([-9, -8, -7])

In [30]:
tensor*10

tensor([10, 20, 30])

###Matrix Multiplication

In [31]:
%%time
#Element wise multiplication
value=0
for i in range(len(tensor)):
  value+=tensor[i]*10
print(value)

tensor(60)
CPU times: user 3.63 ms, sys: 0 ns, total: 3.63 ms
Wall time: 8.07 ms


In [32]:
%%time
t1=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
t2=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
torch.matmul(t1,t2)

CPU times: user 1.39 ms, sys: 243 µs, total: 1.64 ms
Wall time: 5.14 ms


tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

###Facts
* @ operator can also be used
* The same rules of matrix multiplication will also get applied
* Compatible multiplcation : inner dimensions must be the same eg: (3,2) & (2,3) will work
* Also the resulting matrix will be (3,3)

In [33]:
%%time
t1@t2

CPU times: user 85 µs, sys: 15 µs, total: 100 µs
Wall time: 103 µs


tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

##To fix tensor shape issues, we can use transpose
* transpose switches the axes

In [34]:
 t1=torch.rand(size=(3,4))
 t2=torch.rand(size=(3,4))
 torch.matmul(t1,t2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 3x4)

In [35]:
#using transpose to change the shape of t2
torch.matmul(t1,t2.T)

tensor([[0.9727, 0.9217, 0.8437],
        [1.8837, 1.5979, 1.7345],
        [1.5584, 1.3147, 1.4486]])

###Tensor Aggregation

In [36]:
x=torch.arange(0,100,10)

In [37]:
torch.min(x),torch.max(x),x.min(),x.max()

(tensor(0), tensor(90), tensor(0), tensor(90))

In [38]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [39]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

### Positional min and max

In [40]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
x.argmin(),x.argmax()

(tensor(0), tensor(9))

### Operations
* Reshape
* View : In case of view, the `variable` storing the view will also have the same memory so the changes made to this variable will also get reflected in the original variable
* Stack

In [42]:
tensor=torch.rand(100)
tensor,tensor.shape

(tensor([0.4807, 0.1076, 0.1863, 0.9704, 0.2994, 0.1246, 0.1947, 0.8415, 0.3367,
         0.0030, 0.1332, 0.0341, 0.3125, 0.1576, 0.7974, 0.6860, 0.7589, 0.5569,
         0.2840, 0.3375, 0.8454, 0.2127, 0.9774, 0.9725, 0.6903, 0.6539, 0.7460,
         0.9622, 0.9296, 0.5532, 0.4769, 0.9903, 0.4775, 0.1844, 0.4417, 0.1032,
         0.7070, 0.0665, 0.1570, 0.5937, 0.6616, 0.7345, 0.6777, 0.0250, 0.9397,
         0.0458, 0.5868, 0.3862, 0.3281, 0.6471, 0.0505, 0.2261, 0.3842, 0.1641,
         0.0021, 0.7333, 0.4355, 0.2045, 0.6163, 0.2998, 0.6941, 0.4017, 0.1062,
         0.6571, 0.2698, 0.9545, 0.4288, 0.7225, 0.5934, 0.1651, 0.9396, 0.2946,
         0.5941, 0.0856, 0.9305, 0.4802, 0.9113, 0.1449, 0.7737, 0.2582, 0.6674,
         0.8478, 0.4746, 0.9034, 0.2528, 0.7868, 0.8596, 0.8702, 0.6121, 0.7659,
         0.3440, 0.1919, 0.2985, 0.9610, 0.4521, 0.9320, 0.6760, 0.8019, 0.6436,
         0.7431]),
 torch.Size([100]))

In [43]:
z=tensor.reshape(1,100)
z,z.shape

(tensor([[0.4807, 0.1076, 0.1863, 0.9704, 0.2994, 0.1246, 0.1947, 0.8415, 0.3367,
          0.0030, 0.1332, 0.0341, 0.3125, 0.1576, 0.7974, 0.6860, 0.7589, 0.5569,
          0.2840, 0.3375, 0.8454, 0.2127, 0.9774, 0.9725, 0.6903, 0.6539, 0.7460,
          0.9622, 0.9296, 0.5532, 0.4769, 0.9903, 0.4775, 0.1844, 0.4417, 0.1032,
          0.7070, 0.0665, 0.1570, 0.5937, 0.6616, 0.7345, 0.6777, 0.0250, 0.9397,
          0.0458, 0.5868, 0.3862, 0.3281, 0.6471, 0.0505, 0.2261, 0.3842, 0.1641,
          0.0021, 0.7333, 0.4355, 0.2045, 0.6163, 0.2998, 0.6941, 0.4017, 0.1062,
          0.6571, 0.2698, 0.9545, 0.4288, 0.7225, 0.5934, 0.1651, 0.9396, 0.2946,
          0.5941, 0.0856, 0.9305, 0.4802, 0.9113, 0.1449, 0.7737, 0.2582, 0.6674,
          0.8478, 0.4746, 0.9034, 0.2528, 0.7868, 0.8596, 0.8702, 0.6121, 0.7659,
          0.3440, 0.1919, 0.2985, 0.9610, 0.4521, 0.9320, 0.6760, 0.8019, 0.6436,
          0.7431]]),
 torch.Size([1, 100]))

In [44]:
w=tensor.view(10,10)
w,w.shape

(tensor([[0.4807, 0.1076, 0.1863, 0.9704, 0.2994, 0.1246, 0.1947, 0.8415, 0.3367,
          0.0030],
         [0.1332, 0.0341, 0.3125, 0.1576, 0.7974, 0.6860, 0.7589, 0.5569, 0.2840,
          0.3375],
         [0.8454, 0.2127, 0.9774, 0.9725, 0.6903, 0.6539, 0.7460, 0.9622, 0.9296,
          0.5532],
         [0.4769, 0.9903, 0.4775, 0.1844, 0.4417, 0.1032, 0.7070, 0.0665, 0.1570,
          0.5937],
         [0.6616, 0.7345, 0.6777, 0.0250, 0.9397, 0.0458, 0.5868, 0.3862, 0.3281,
          0.6471],
         [0.0505, 0.2261, 0.3842, 0.1641, 0.0021, 0.7333, 0.4355, 0.2045, 0.6163,
          0.2998],
         [0.6941, 0.4017, 0.1062, 0.6571, 0.2698, 0.9545, 0.4288, 0.7225, 0.5934,
          0.1651],
         [0.9396, 0.2946, 0.5941, 0.0856, 0.9305, 0.4802, 0.9113, 0.1449, 0.7737,
          0.2582],
         [0.6674, 0.8478, 0.4746, 0.9034, 0.2528, 0.7868, 0.8596, 0.8702, 0.6121,
          0.7659],
         [0.3440, 0.1919, 0.2985, 0.9610, 0.4521, 0.9320, 0.6760, 0.8019, 0.6436,
         

In [45]:
tensor=tensor.reshape(10,10)
tensor,tensor.shape

(tensor([[0.4807, 0.1076, 0.1863, 0.9704, 0.2994, 0.1246, 0.1947, 0.8415, 0.3367,
          0.0030],
         [0.1332, 0.0341, 0.3125, 0.1576, 0.7974, 0.6860, 0.7589, 0.5569, 0.2840,
          0.3375],
         [0.8454, 0.2127, 0.9774, 0.9725, 0.6903, 0.6539, 0.7460, 0.9622, 0.9296,
          0.5532],
         [0.4769, 0.9903, 0.4775, 0.1844, 0.4417, 0.1032, 0.7070, 0.0665, 0.1570,
          0.5937],
         [0.6616, 0.7345, 0.6777, 0.0250, 0.9397, 0.0458, 0.5868, 0.3862, 0.3281,
          0.6471],
         [0.0505, 0.2261, 0.3842, 0.1641, 0.0021, 0.7333, 0.4355, 0.2045, 0.6163,
          0.2998],
         [0.6941, 0.4017, 0.1062, 0.6571, 0.2698, 0.9545, 0.4288, 0.7225, 0.5934,
          0.1651],
         [0.9396, 0.2946, 0.5941, 0.0856, 0.9305, 0.4802, 0.9113, 0.1449, 0.7737,
          0.2582],
         [0.6674, 0.8478, 0.4746, 0.9034, 0.2528, 0.7868, 0.8596, 0.8702, 0.6121,
          0.7659],
         [0.3440, 0.1919, 0.2985, 0.9610, 0.4521, 0.9320, 0.6760, 0.8019, 0.6436,
         

In [46]:
tensor=torch.arange(10)
tensor,tensor.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

###horizontal and vertical stack

In [47]:
torch.stack([tensor,tensor],dim=0)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [48]:
torch.stack([tensor,tensor],dim=1)

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4],
        [5, 5],
        [6, 6],
        [7, 7],
        [8, 8],
        [9, 9]])

###Facts
* squeeze : removes the `1` dimension
* unsqueeze : adds up the `1` dimension
* permute : rearranges the dimensions

In [49]:
tensor=torch.rand(1,100)
tensor,tensor.shape

(tensor([[0.6919, 0.7006, 0.7060, 0.3249, 0.9423, 0.8738, 0.5751, 0.2584, 0.6093,
          0.6421, 0.5374, 0.1946, 0.6327, 0.9581, 0.0425, 0.5744, 0.1425, 0.8829,
          0.9092, 0.9538, 0.3406, 0.8009, 0.7959, 0.2031, 0.4283, 0.8863, 0.4349,
          0.7661, 0.8088, 0.8483, 0.9275, 0.0723, 0.2792, 0.3839, 0.2144, 0.8227,
          0.5429, 0.2581, 0.7366, 0.0027, 0.3271, 0.9098, 0.4916, 0.9472, 0.6275,
          0.0751, 0.9559, 0.7799, 0.5182, 0.6701, 0.6864, 0.5232, 0.1782, 0.9506,
          0.0529, 0.9373, 0.5263, 0.6975, 0.6710, 0.7097, 0.4833, 0.6532, 0.0502,
          0.3911, 0.9587, 0.3773, 0.8393, 0.3185, 0.0475, 0.1672, 0.9121, 0.8496,
          0.6935, 0.0205, 0.0312, 0.1277, 0.3949, 0.3896, 0.7738, 0.9376, 0.6856,
          0.4532, 0.1599, 0.5432, 0.1566, 0.6555, 0.7652, 0.1114, 0.7527, 0.0763,
          0.8749, 0.5391, 0.8993, 0.5768, 0.6525, 0.2776, 0.7485, 0.9726, 0.9438,
          0.7167]]),
 torch.Size([1, 100]))

In [50]:
torch.squeeze(tensor)

tensor([0.6919, 0.7006, 0.7060, 0.3249, 0.9423, 0.8738, 0.5751, 0.2584, 0.6093,
        0.6421, 0.5374, 0.1946, 0.6327, 0.9581, 0.0425, 0.5744, 0.1425, 0.8829,
        0.9092, 0.9538, 0.3406, 0.8009, 0.7959, 0.2031, 0.4283, 0.8863, 0.4349,
        0.7661, 0.8088, 0.8483, 0.9275, 0.0723, 0.2792, 0.3839, 0.2144, 0.8227,
        0.5429, 0.2581, 0.7366, 0.0027, 0.3271, 0.9098, 0.4916, 0.9472, 0.6275,
        0.0751, 0.9559, 0.7799, 0.5182, 0.6701, 0.6864, 0.5232, 0.1782, 0.9506,
        0.0529, 0.9373, 0.5263, 0.6975, 0.6710, 0.7097, 0.4833, 0.6532, 0.0502,
        0.3911, 0.9587, 0.3773, 0.8393, 0.3185, 0.0475, 0.1672, 0.9121, 0.8496,
        0.6935, 0.0205, 0.0312, 0.1277, 0.3949, 0.3896, 0.7738, 0.9376, 0.6856,
        0.4532, 0.1599, 0.5432, 0.1566, 0.6555, 0.7652, 0.1114, 0.7527, 0.0763,
        0.8749, 0.5391, 0.8993, 0.5768, 0.6525, 0.2776, 0.7485, 0.9726, 0.9438,
        0.7167])

In [51]:
tensor=torch.arange(10)
tensor,tensor.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [52]:
torch.unsqueeze(tensor,0)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [53]:
tensor=tensor.reshape(1,10)
tensor.permute(1,0)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

###Indexing : getting specific data from tensors

In [54]:
import torch

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [58]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [57]:
x[0][2]

tensor([7, 8, 9])

In [60]:
x[0][2][2]

tensor(9)

In [61]:
x[0,2]

tensor([7, 8, 9])

###we can also use `:` for choosing all the values of that particular tensor

In [65]:
x[:,:,:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [66]:
x[:,2]

tensor([[7, 8, 9]])

In [74]:
x[:,:,2]

tensor([[3, 6, 9]])

In [72]:
x[:,1,:]

tensor([[4, 5, 6]])

In [73]:
x[:,2,2]

tensor([9])

###PyTorch and NumPy
* Numpy to Tensor : `tensor.from_numpy()`
* Tensor to Numpy : `torch.Tensor.numpy()`
* Default datatype of numpy : `float64`
* Default datatype of tensor : `float32`

In [75]:
import torch
import numpy as np

#Numpy to tensor
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [76]:
array.dtype

dtype('float64')

In [77]:
torch.arange(1.0,10.0).dtype

torch.float32

In [78]:
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [79]:
#Tensor to Numpy
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [81]:
tensor=tensor+2
numpy_tensor,tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([3., 3., 3., 3., 3., 3., 3.]))

###Random seed
* In neural networks, intially random tensors are used and eventually they are adjusted to fit the data in a better manner
* So, here even though the tensors are generated manually inorder to `flavour the randomness`(to create some sort of smilarity) we use `random seed`

In [83]:
import torch

t1=torch.rand(3,2)
t2=torch.rand(3,2)

print(t1)
print(t2)
print(t1==t2)

tensor([[0.2566, 0.7936],
        [0.9408, 0.1332],
        [0.9346, 0.5936]])
tensor([[0.8694, 0.5677],
        [0.7411, 0.4294],
        [0.8854, 0.5739]])
tensor([[False, False],
        [False, False],
        [False, False]])


In [82]:
import torch

RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
t1=torch.rand(3,2)

torch.manual_seed(RANDOM_SEED)
t2=torch.rand(3,2)

print(t1)
print(t2)
print(t1==t2)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009]])
tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009]])
tensor([[True, True],
        [True, True],
        [True, True]])


###Running tensors and PyTorch on GPUs

In [1]:
!nvidia-smi

Thu Jun 13 13:55:26 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
#Device Agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
#Count number of devices
torch.cuda.device_count()

1

###Running tensors and models on GPUs become faster

In [5]:
#Tensors by defaut get created on CPUs
tensor=torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


* The above `torch.device` specifies the device on which the tensors are located
* In the next code cell, `torch.to(device)` changes the device; this is possible only due to the device `agnostic code` written earlier

In [6]:
#On GPU
tensor_on_gpu=tensor.to(device)
tensor_on_gpu,tensor_on_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

* `numpy` can only work inside the cpu
* `tensor.numpy()` converts tensors to numpy

In [7]:
#Numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [8]:
#Solving the error
tensor_on_cpu=tensor_on_gpu.cpu()
tensor_on_cpu,tensor_on_cpu.device

(tensor([1, 2, 3]), device(type='cpu'))

In [9]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')