<a href="https://colab.research.google.com/github/govardhan-06/Colab-Notebooks/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

###Scalars, Vectors, Tensors and Matrix

In [ ]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.shape

torch.Size([])

In [ ]:
 #vector
 vector=torch.tensor([7,8])
 vector

tensor([7, 8])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
vector[1]

tensor(8)

In [ ]:
#matrix
matrix=torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
matrix[1]

tensor([ 9, 10])

In [ ]:
#tensor
tensor=torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor[0][1][1]

tensor(6)

###Random Tensors and Random image tensor


In [ ]:
#Random Tensors
torch.rand(2,2,4)

tensor([[[0.9684, 0.3333, 0.0849, 0.4758],
         [0.7404, 0.3857, 0.8811, 0.2000]],

        [[0.8630, 0.6025, 0.9371, 0.5015],
         [0.5643, 0.4438, 0.6194, 0.3348]]])

In [ ]:
#Random image tensors
randm_image_size_tensor=torch.rand(size=(224,224,3))
randm_image_size_tensor.shape,randm_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###Zeros and Ones

In [ ]:
zeros=torch.zeros(size=(3,5))
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
ones=torch.ones(size=(1,4))
ones

tensor([[1., 1., 1., 1.]])

###Range of tensors and tensors like

In [ ]:
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor Datatypes

In [ ]:
float_32_tensor=torch.tensor(data=[3.0,6.0,9.0],
                             dtype=None,
                             device=None,
                             requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor*float_16_tensor

tensor([ 9., 36., 81.])

###Basic tensor related functions

In [ ]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.8816, 0.0106, 0.9409, 0.9496],
        [0.0614, 0.9778, 0.9504, 0.5509],
        [0.5163, 0.2909, 0.9220, 0.9486]])

In [ ]:
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Device tensor is stored on : {some_tensor.device}")

Shape of tensor : torch.Size([3, 4])
Datatype of tensor : torch.float32
Device tensor is stored on : cpu


###Tensor operations
* Addition
* Subtract
* Multiply
* Divide
* Matrix Multiplication


In [ ]:
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor-10

tensor([-9, -8, -7])

In [ ]:
tensor*10

tensor([10, 20, 30])

###Matrix Multiplication

In [ ]:
%%time
#Element wise multiplication
value=0
for i in range(len(tensor)):
  value+=tensor[i]*10
print(value)

tensor(60)
CPU times: user 4.23 ms, sys: 7 µs, total: 4.24 ms
Wall time: 9.82 ms


In [ ]:
%%time
t1=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
t2=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
torch.matmul(t1,t2)

CPU times: user 1.48 ms, sys: 20 µs, total: 1.5 ms
Wall time: 1.45 ms


tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

###Facts
* @ operator can also be used
* The same rules of matrix multiplication will also get applied
* Compatible multiplcation : inner dimensions must be the same eg: (3,2) & (2,3) will work
* Also the resulting matrix will be (3,3)

In [ ]:
%%time
t1@t2

CPU times: user 1.28 ms, sys: 19 µs, total: 1.3 ms
Wall time: 1.22 ms


tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

##To fix tensor shape issues, we can use transpose
* transpose switches the axes

In [ ]:
 t1=torch.rand(size=(3,4))
 t2=torch.rand(size=(3,4))
 torch.matmul(t1,t2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 3x4)

In [ ]:
#using transpose to change the shape of t2
torch.matmul(t1,t2.T)

tensor([[0.8519, 1.5641, 0.8335],
        [1.2161, 1.3169, 1.1377],
        [1.1432, 1.9284, 1.3323]])

###Tensor Aggregation

In [ ]:
x=torch.arange(0,100,10)

In [ ]:
torch.min(x),torch.max(x),x.min(),x.max()

(tensor(0), tensor(90), tensor(0), tensor(90))

In [ ]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

### Positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin(),x.argmax()

(tensor(0), tensor(9))

### Operations
* Reshape
* View : In case of view, the `variable` storing the view will also have the same memory so the changes made to this variable will also get reflected in the original variable
* Stack

In [ ]:
tensor=torch.rand(100)
tensor,tensor.shape

(tensor([0.3808, 0.3115, 0.8228, 0.7183, 0.1369, 0.1323, 0.7788, 0.1368, 0.7800,
         0.3908, 0.0466, 0.3011, 0.7239, 0.6330, 0.5647, 0.8549, 0.1525, 0.0425,
         0.3239, 0.3187, 0.4570, 0.3970, 0.3917, 0.1329, 0.1372, 0.3292, 0.7983,
         0.1133, 0.8012, 0.7931, 0.5063, 0.3810, 0.7565, 0.4438, 0.1473, 0.2576,
         0.6319, 0.6749, 0.6659, 0.9643, 0.8592, 0.6821, 0.8095, 0.2734, 0.5191,
         0.0635, 0.6409, 0.6393, 0.8220, 0.5320, 0.3526, 0.4586, 0.8341, 0.7759,
         0.1566, 0.6745, 0.6436, 0.5727, 0.7061, 0.1567, 0.7798, 0.1200, 0.5298,
         0.7034, 0.0702, 0.4837, 0.7348, 0.7784, 0.4125, 0.9212, 0.2718, 0.4478,
         0.9927, 0.3597, 0.1374, 0.8231, 0.4655, 0.5096, 0.1060, 0.4033, 0.3047,
         0.3572, 0.5812, 0.1325, 0.0763, 0.9746, 0.3494, 0.1538, 0.7807, 0.4954,
         0.2047, 0.6789, 0.9843, 0.8261, 0.5310, 0.8362, 0.8185, 0.6450, 0.8801,
         0.8772]),
 torch.Size([100]))

In [ ]:
z=tensor.reshape(1,100)
z,z.shape

(tensor([[0.7107, 0.9675, 0.0380, 0.8073, 0.0662, 0.1962, 0.1584, 0.5500, 0.0050,
          0.4121, 0.3911, 0.0634, 0.5410, 0.4191, 0.2614, 0.7627, 0.7843, 0.6388,
          0.1268, 0.6632, 0.4143, 0.5403, 0.2447, 0.6421, 0.7984, 0.3333, 0.6822,
          0.4176, 0.2602, 0.7557, 0.0761, 0.1367, 0.6574, 0.2307, 0.7813, 0.5192,
          0.0310, 0.7384, 0.6301, 0.7189, 0.5917, 0.7118, 0.2543, 0.1997, 0.9681,
          0.6121, 0.9701, 0.1724, 0.2499, 0.9035, 0.3986, 0.6930, 0.9479, 0.6736,
          0.5986, 0.8222, 0.4103, 0.5373, 0.4875, 0.1341, 0.5075, 0.0863, 0.7698,
          0.0319, 0.3559, 0.8929, 0.6408, 0.4093, 0.7793, 0.9699, 0.4334, 0.0957,
          0.6005, 0.2951, 0.2953, 0.7896, 0.8109, 0.5925, 0.7355, 0.9276, 0.2850,
          0.2748, 0.5060, 0.9319, 0.2332, 0.6782, 0.0660, 0.2637, 0.2639, 0.9093,
          0.6895, 0.3741, 0.7240, 0.3557, 0.1694, 0.8036, 0.6406, 0.4557, 0.1483,
          0.8291]]),
 torch.Size([1, 100]))

In [ ]:
w=tensor.view(10,10)
w,w.shape

(tensor([[0.3808, 0.3115, 0.8228, 0.7183, 0.1369, 0.1323, 0.7788, 0.1368, 0.7800,
          0.3908],
         [0.0466, 0.3011, 0.7239, 0.6330, 0.5647, 0.8549, 0.1525, 0.0425, 0.3239,
          0.3187],
         [0.4570, 0.3970, 0.3917, 0.1329, 0.1372, 0.3292, 0.7983, 0.1133, 0.8012,
          0.7931],
         [0.5063, 0.3810, 0.7565, 0.4438, 0.1473, 0.2576, 0.6319, 0.6749, 0.6659,
          0.9643],
         [0.8592, 0.6821, 0.8095, 0.2734, 0.5191, 0.0635, 0.6409, 0.6393, 0.8220,
          0.5320],
         [0.3526, 0.4586, 0.8341, 0.7759, 0.1566, 0.6745, 0.6436, 0.5727, 0.7061,
          0.1567],
         [0.7798, 0.1200, 0.5298, 0.7034, 0.0702, 0.4837, 0.7348, 0.7784, 0.4125,
          0.9212],
         [0.2718, 0.4478, 0.9927, 0.3597, 0.1374, 0.8231, 0.4655, 0.5096, 0.1060,
          0.4033],
         [0.3047, 0.3572, 0.5812, 0.1325, 0.0763, 0.9746, 0.3494, 0.1538, 0.7807,
          0.4954],
         [0.2047, 0.6789, 0.9843, 0.8261, 0.5310, 0.8362, 0.8185, 0.6450, 0.8801,
         

In [ ]:
tensor=tensor.reshape(10,10)
tensor,tensor.shape

(tensor([[3.8084e-01, 1.0000e+03, 8.2279e-01, 7.1832e-01, 1.3687e-01, 1.3226e-01,
          7.7881e-01, 1.3682e-01, 7.7998e-01, 3.9078e-01],
         [4.6602e-02, 3.0107e-01, 7.2390e-01, 6.3304e-01, 5.6465e-01, 8.5491e-01,
          1.5255e-01, 4.2458e-02, 3.2393e-01, 3.1868e-01],
         [4.5704e-01, 3.9703e-01, 3.9169e-01, 1.3288e-01, 1.3718e-01, 3.2920e-01,
          7.9835e-01, 1.1334e-01, 8.0122e-01, 7.9314e-01],
         [5.0630e-01, 3.8101e-01, 7.5655e-01, 4.4379e-01, 1.4732e-01, 2.5760e-01,
          6.3193e-01, 6.7495e-01, 6.6593e-01, 9.6429e-01],
         [8.5917e-01, 6.8214e-01, 8.0948e-01, 2.7335e-01, 5.1911e-01, 6.3460e-02,
          6.4087e-01, 6.3933e-01, 8.2205e-01, 5.3202e-01],
         [3.5259e-01, 4.5857e-01, 8.3412e-01, 7.7590e-01, 1.5660e-01, 6.7446e-01,
          6.4364e-01, 5.7269e-01, 7.0606e-01, 1.5669e-01],
         [7.7977e-01, 1.2004e-01, 5.2979e-01, 7.0338e-01, 7.0167e-02, 4.8366e-01,
          7.3484e-01, 7.7841e-01, 4.1249e-01, 9.2122e-01],
         [2.7

In [ ]:
tensor=torch.arange(10)
tensor,tensor.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [ ]:
torch.stack([tensor,tensor],dim=0)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
torch.stack([tensor,tensor],dim=1)

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4],
        [5, 5],
        [6, 6],
        [7, 7],
        [8, 8],
        [9, 9]])

###Facts
* squeeze : removes the `1` dimension
* unsqueeze : adds up the `1` dimension
* permute : rearranges the dimensions

In [78]:
tensor=torch.rand(1,100)
tensor,tensor.shape

(tensor([[0.9615, 0.3882, 0.0470, 0.6023, 0.3430, 0.6139, 0.3559, 0.6105, 0.0967,
          0.9885, 0.2196, 0.7162, 0.2231, 0.6180, 0.7364, 0.4993, 0.5298, 0.3260,
          0.0790, 0.2781, 0.5429, 0.8521, 0.7826, 0.6366, 0.4617, 0.2571, 0.0753,
          0.7602, 0.3339, 0.5613, 0.2187, 0.4230, 0.8822, 0.9690, 0.6639, 0.3712,
          0.0344, 0.1551, 0.2187, 0.2480, 0.4503, 0.0947, 0.4438, 0.0151, 0.8576,
          0.8233, 0.9076, 0.7437, 0.1336, 0.9811, 0.1311, 0.6103, 0.1660, 0.3477,
          0.6603, 0.7973, 0.6510, 0.6969, 0.0921, 0.6107, 0.0345, 0.9361, 0.1118,
          0.7993, 0.3012, 0.0669, 0.2653, 0.9632, 0.6115, 0.2585, 0.6048, 0.4796,
          0.0562, 0.8501, 0.7045, 0.0795, 0.8246, 0.3182, 0.3121, 0.7123, 0.1343,
          0.5472, 0.0926, 0.9406, 0.2013, 0.9029, 0.3624, 0.7704, 0.6033, 0.7115,
          0.4759, 0.1398, 0.8985, 0.1196, 0.3690, 0.9617, 0.7820, 0.8807, 0.9891,
          0.4991]]),
 torch.Size([1, 100]))

In [79]:
torch.squeeze(tensor)

tensor([0.9615, 0.3882, 0.0470, 0.6023, 0.3430, 0.6139, 0.3559, 0.6105, 0.0967,
        0.9885, 0.2196, 0.7162, 0.2231, 0.6180, 0.7364, 0.4993, 0.5298, 0.3260,
        0.0790, 0.2781, 0.5429, 0.8521, 0.7826, 0.6366, 0.4617, 0.2571, 0.0753,
        0.7602, 0.3339, 0.5613, 0.2187, 0.4230, 0.8822, 0.9690, 0.6639, 0.3712,
        0.0344, 0.1551, 0.2187, 0.2480, 0.4503, 0.0947, 0.4438, 0.0151, 0.8576,
        0.8233, 0.9076, 0.7437, 0.1336, 0.9811, 0.1311, 0.6103, 0.1660, 0.3477,
        0.6603, 0.7973, 0.6510, 0.6969, 0.0921, 0.6107, 0.0345, 0.9361, 0.1118,
        0.7993, 0.3012, 0.0669, 0.2653, 0.9632, 0.6115, 0.2585, 0.6048, 0.4796,
        0.0562, 0.8501, 0.7045, 0.0795, 0.8246, 0.3182, 0.3121, 0.7123, 0.1343,
        0.5472, 0.0926, 0.9406, 0.2013, 0.9029, 0.3624, 0.7704, 0.6033, 0.7115,
        0.4759, 0.1398, 0.8985, 0.1196, 0.3690, 0.9617, 0.7820, 0.8807, 0.9891,
        0.4991])

In [84]:
tensor=torch.arange(10)
tensor,tensor.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [86]:
torch.unsqueeze(tensor,0)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [95]:
tensor=tensor.reshape(1,10)
tensor.permute(1,0)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])